<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Observability" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Web" />
    <ProjectReference Include="../SwiftBets.Offer.Infrastructure/SwiftBets.Offer.Infrastructure.csproj" />
  </ItemGroup>
</Project>
