<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Testing" />
    <ProjectReference Include="../../src/SwiftBets.Offer.Infrastructure/SwiftBets.Offer.Infrastructure.csproj" />
    <ProjectReference Include="../../src/SwiftBets.Offer.Migrator/SwiftBets.Offer.Migrator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>
</Project>
