<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Core" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Messaging" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Redis" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <ProjectReference Include="../SwiftBets.Offer.Application/SwiftBets.Offer.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data/*.json" />
    <EmbeddedResource Include="Redis/*.lua" />
  </ItemGroup>
</Project>
